// Generate HTML report from JSON audit results
// Usage: node index.js https://api.example.com --json | node report.js > report.html

let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", chunk => { input += chunk; });
process.stdin.on("end", () => {
  const data = JSON.parse(input);
  const pass = data.results.filter(r => r.status === "PASS").length;
  const fail = data.results.filter(r => r.status === "FAIL").length;
  const warn = data.results.filter(r => r.status === "WARN").length;
  const score = Math.round((pass / data.results.length) * 100);
  const grade = score >= 90 ? "A" : score >= 75 ? "B" : score >= 60 ? "C" : score >= 40 ? "D" : "F";
  const gradeColor = score >= 75 ? "#22c55e" : score >= 50 ? "#f59e0b" : "#ef4444";

  const categorize = (cat) => data.results.filter(r => r.category === cat);
  const categories = [...new Set(data.results.map(r => r.category))];

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>API Security Audit — ${data.target}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
  .target { color: #94a3b8; font-size: 0.9rem; margin-bottom: 2rem; }
  .score-card { display: flex; gap: 2rem; margin-bottom: 2rem; padding: 1.5rem; background: #1e293b; border-radius: 12px; }
  .grade { font-size: 4rem; font-weight: 800; color: ${gradeColor}; line-height: 1; }
  .score-details { display: flex; flex-direction: column; justify-content: center; }
  .score-num { font-size: 1.2rem; font-weight: 600; }
  .score-breakdown { color: #94a3b8; font-size: 0.85rem; margin-top: 0.25rem; }
  .pass { color: #22c55e; } .fail { color: #ef4444; } .warn { color: #f59e0b; }
  .category { margin-bottom: 1.5rem; }
  .cat-header { font-size: 1.1rem; font-weight: 600; padding: 0.75rem 1rem; background: #1e293b; border-radius: 8px 8px 0 0; text-transform: uppercase; letter-spacing: 0.05em; }
  .test { padding: 0.6rem 1rem; border-bottom: 1px solid #1e293b; display: flex; align-items: center; gap: 0.75rem; }
  .test:last-child { border-bottom: none; }
  .icon { font-size: 0.8rem; width: 60px; text-align: center; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
  .icon.PASS { background: #052e16; color: #22c55e; }
  .icon.FAIL { background: #450a0a; color: #ef4444; }
  .icon.WARN { background: #451a03; color: #f59e0b; }
  .test-name { flex: 1; font-size: 0.9rem; }
  .test-code { color: #64748b; font-size: 0.8rem; }
  .detail { color: #64748b; font-size: 0.8rem; padding: 0.25rem 1rem 0.5rem 4.5rem; }
  footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #1e293b; color: #475569; font-size: 0.75rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>API Security Audit Report</h1>
  <div class="target">${data.target} — ${new Date().toISOString().slice(0, 10)}</div>

  <div class="score-card">
    <div class="grade">${grade}</div>
    <div class="score-details">
      <div class="score-num">${score}% Security Score</div>
      <div class="score-breakdown">
        <span class="pass">${pass} pass</span> · <span class="fail">${fail} fail</span> · <span class="warn">${warn} warn</span> · ${data.results.length} total
      </div>
    </div>
  </div>

  ${categories.map(cat => {
    const tests = categorize(cat);
    return `<div class="category">
    <div class="cat-header">${cat} (${tests.length})</div>
    ${tests.map(t => `<div class="test">
      <span class="icon ${t.status}">${t.status}</span>
      <span class="test-name">${t.name}</span>
      ${t.statusCode ? `<span class="test-code">${t.statusCode}</span>` : ""}
    </div>${t.detail && t.status !== "PASS" ? `<div class="detail">${String(t.detail).slice(0, 200)}</div>` : ""}`).join("\n")}
  </div>`;
  }).join("\n")}

  <footer>Generated by API Security Audit Kit · github.com/rsbasic/api-audit-kit</footer>
</div>
</body>
</html>`;

  process.stdout.write(html);
});
